# Generated by Django 3.2.9 on 2021-11-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [('StudentGrades', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentGrades.course'))
                #('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentGrades.student'))
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=12)),
            ],
        )
        ,

    migrations.AddField(
        model_name='grade',
        name='student_id',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentGrades.student'),
    ),
    ]
