# Generated by Django 3.2.9 on 2021-11-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentGrades', '0002_auto_20211113_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
    ]
