# Generated by Django 3.2.9 on 2021-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentGrades', '0003_auto_20211113_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='final_term_exam',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='midterm_exam_weight',
            field=models.DecimalField(decimal_places=1, default=0.4, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm_exam',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
