# Generated by Django 3.2.9 on 2021-11-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentGrades', '0004_auto_20211114_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='midterm_exam_weight',
            field=models.DecimalField(decimal_places=1, default=0.3, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentGrades.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentGrades.student'),
        ),
    ]
